# This workflow will upload the NumWorks Canvas Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: NumWorks Canvas

# on:
#   release:
#     types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Python 3.8 for compatibility with NumWorks calculators

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  # Install build tool for packaging

    - name: Build package
      run: python -m build  # Build the package

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.2.3  # Publish to PyPI
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}  # Token for authentication
